@echo off
echo Starting Flutter Team Sync App...
echo.
echo Cleaning previous builds...
flutter clean
echo.
echo Getting dependencies...
flutter pub get
echo.
echo Starting app on Edge browser...
set CHROME_EXECUTABLE="C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
flutter run -d chrome --web-port=8081 --web-renderer=html
