// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdk_dktdHQ2RnVMxugVdbxk0E6pJlvWBc',
    appId: '1:310750228851:web:your_web_app_id',
    messagingSenderId: '310750228851',
    projectId: 'team-sync-project-management',
    authDomain: 'team-sync-project-management.firebaseapp.com',
    storageBucket: 'team-sync-project-management.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdk_dktdHQ2RnVMxugVdbxk0E6pJlvWBc',
    appId: '1:310750228851:android:0f9170f979cab3d6769506',
    messagingSenderId: '310750228851',
    projectId: 'team-sync-project-management',
    storageBucket: 'team-sync-project-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdk_dktdHQ2RnVMxugVdbxk0E6pJlvWBc',
    appId: '1:310750228851:ios:your_ios_app_id',
    messagingSenderId: '310750228851',
    projectId: 'team-sync-project-management',
    storageBucket: 'team-sync-project-management.appspot.com',
    iosBundleId: 'com.example.fluttercomponenets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdk_dktdHQ2RnVMxugVdbxk0E6pJlvWBc',
    appId: '1:310750228851:ios:your_ios_app_id',
    messagingSenderId: '310750228851',
    projectId: 'team-sync-project-management',
    storageBucket: 'team-sync-project-management.appspot.com',
    iosBundleId: 'com.example.fluttercomponenets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdk_dktdHQ2RnVMxugVdbxk0E6pJlvWBc',
    appId: '1:310750228851:web:your_web_app_id',
    messagingSenderId: '310750228851',
    projectId: 'team-sync-project-management',
    authDomain: 'team-sync-project-management.firebaseapp.com',
    storageBucket: 'team-sync-project-management.appspot.com',
  );
}
