// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZn44p34ZWqD9Ih-kpi7XXTuKVbW1ug0s',
    appId: '1:20508462372:web:edb0c2158fc00d65aff7b1',
    messagingSenderId: '20508462372',
    projectId: 'teamsync-c5068',
    authDomain: 'teamsync-c5068.firebaseapp.com',
    storageBucket: 'teamsync-c5068.firebasestorage.app',
    measurementId: 'G-FV57HLP81T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYE7YoP36lw6YtAr7SuX2DcnY4nECNA_g',
    appId: '1:20508462372:android:07bf4657ad47c84faff7b1',
    messagingSenderId: '20508462372',
    projectId: 'teamsync-c5068',
    storageBucket: 'teamsync-c5068.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ogiLHsJ9Ki12mS2WOoD1k7mUvMNLamY',
    appId: '1:20508462372:ios:e14e36ecb34fbc55aff7b1',
    messagingSenderId: '20508462372',
    projectId: 'teamsync-c5068',
    storageBucket: 'teamsync-c5068.firebasestorage.app',
    iosBundleId: 'com.example.fluttercomponenets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ogiLHsJ9Ki12mS2WOoD1k7mUvMNLamY',
    appId: '1:20508462372:ios:e14e36ecb34fbc55aff7b1',
    messagingSenderId: '20508462372',
    projectId: 'teamsync-c5068',
    storageBucket: 'teamsync-c5068.firebasestorage.app',
    iosBundleId: 'com.example.fluttercomponenets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZn44p34ZWqD9Ih-kpi7XXTuKVbW1ug0s',
    appId: '1:20508462372:web:5f62501cb7e39283aff7b1',
    messagingSenderId: '20508462372',
    projectId: 'teamsync-c5068',
    authDomain: 'teamsync-c5068.firebaseapp.com',
    storageBucket: 'teamsync-c5068.firebasestorage.app',
    measurementId: 'G-BWE80J660D',
  );

}