// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVJKbtYlzrCeE_lc1ACN5oC1hDjPq8hyM',
    appId: '1:3261747080:web:6d299bcc42432b4e9b743d',
    messagingSenderId: '3261747080',
    projectId: 'teamsynclogin',
    authDomain: 'teamsynclogin.firebaseapp.com',
    storageBucket: 'teamsynclogin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8C5HKOuzchaF-cZC_kJiOu3UXhZofOXk',
    appId: '1:3261747080:android:7421d6ea90de34d09b743d',
    messagingSenderId: '3261747080',
    projectId: 'teamsynclogin',
    storageBucket: 'teamsynclogin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPt1dyqSAXmJOWE0wNQ0AqUOk7js3Qmy4',
    appId: '1:3261747080:ios:b529bc21167464bc9b743d',
    messagingSenderId: '3261747080',
    projectId: 'teamsynclogin',
    storageBucket: 'teamsynclogin.firebasestorage.app',
    iosBundleId: 'com.example.fluttercomponenets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPt1dyqSAXmJOWE0wNQ0AqUOk7js3Qmy4',
    appId: '1:3261747080:ios:b529bc21167464bc9b743d',
    messagingSenderId: '3261747080',
    projectId: 'teamsynclogin',
    storageBucket: 'teamsynclogin.firebasestorage.app',
    iosBundleId: 'com.example.fluttercomponenets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVJKbtYlzrCeE_lc1ACN5oC1hDjPq8hyM',
    appId: '1:3261747080:web:844b6d0c64cc49f09b743d',
    messagingSenderId: '3261747080',
    projectId: 'teamsynclogin',
    authDomain: 'teamsynclogin.firebaseapp.com',
    storageBucket: 'teamsynclogin.firebasestorage.app',
  );
}
